version: "3"

services:
  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"
    volumes:
      - './config/etc-unbound/:/opt/unbound/etc/unbound/'
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file:
      - .env
    volumes:
      - './config/etc-pihole/:/etc/pihole/'
      - './config/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped
